const mockEvents = {
  city: {
    id: 603134,
    city: 'Waterloo',
    lat: 43.47,
    lon: -80.51,
    state: 'ON',
    country: 'ca',
    zip: 'N2J 0A1',
    member_count: 1782
  },
  events: [
    {
      created: 1578410603000,
      duration: 7200000,
      id: '267719029',
      name: 'YSP KW: Starting in Sales ',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1582761600000,
      local_date: '2020-02-25',
      local_time: '19:00',
      updated: 1579558019000,
      utc_offset: -18000000,
      waitlist_count: 0,
      yes_rsvp_count: 49,
      venue: {
        id: 26093718,
        name: 'Communitech',
        lat: 43.451377868652344,
        lon: -80.49877166748047,
        repinned: true,
        address_1: '151 Charles St W #100',
        city: 'Kitchener',
        country: 'ca',
        localized_country_name: 'Canada',
        zip: 'N2G 1H6',
        state: 'ON'
      },
      group: {
        created: 1566325014000,
        name: 'Young Sales Professionals KW',
        id: 32638497,
        join_mode: 'open',
        lat: 43.439998626708984,
        lon: -80.43000030517578,
        urlname: 'YSPKWC',
        who: 'Members',
        localized_location: 'Kitchener, ON',
        state: 'ON',
        country: 'ca',
        region: 'en_US',
        timezone: 'Canada/Eastern'
      },
      link: 'https://www.meetup.com/YSPKWC/events/267719029/',
      description: '<p>YSP is a P2P networking group for beginner sales professionals in the Waterloo Region.</p> <p>The Topic of this event is Starting in Sales, a panel discussion on how each of our speakers developed their impressive careers starting in a sales role. This is a great opportunity to not only to hear from executives in the KW area but connect with your peers to build a community!</p> <p>Drinks provided sponsored by Descendants Beer &amp; Beverage Co.</p> <p>Our Speakers:<br/>Marko Savic - Chief Executive Officer at FunnelCake<br/>Jacqui Murphy - Chief Marketing Officer at Auvik Networks<br/>Nigel Vanderlinden - Chief Revenue Officer at Plum.io</p> <p>6:30 Open Doors and Mingle<br/>7:00 Panel Discussion<br/>7:45 Facilitated Networking</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1581972568000,
      duration: 10800000,
      id: '268784353',
      name: 'Music Bingo at Descendants Brewery',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1582243200000,
      local_date: '2020-02-26',
      local_time: '19:00',
      updated: 1581980733000,
      utc_offset: -18000000,
      waitlist_count: 0,
      yes_rsvp_count: 14,
      venue: {
        id: 24652020,
        name: 'Descendants Beer & Beverage Co.',
        lat: 43.45794677734375,
        lon: -80.48374938964844,
        repinned: false,
        address_1: '319 Victoria St. North',
        city: 'Kitchener',
        country: 'ca',
        localized_country_name: 'Canada',
        zip: '',
        state: 'ON'
      },
      group: {
        created: 1307896090000,
        name: 'Kitchener & Waterloo 20\'s - 30\'s Social Meetup',
        id: 2009211,
        join_mode: 'approval',
        lat: 43.459999084472656,
        lon: -80.4800033569336,
        urlname: 'Kitchener-Waterloo-20s-to-30s-Meetup-Group',
        who: 'Socialites',
        localized_location: 'Kitchener, ON',
        state: 'ON',
        country: 'ca',
        region: 'en_US',
        timezone: 'Canada/Eastern'
      },
      link: 'https://www.meetup.com/Kitchener-Waterloo-20s-to-30s-Meetup-Group/events/268784353/',
      description: '<p>This is a free event, but purchase of a beverage or food is encouraged.</p> <p>Join us for drinks at 7pm. Music Bingo will kick off at 8pm. The theme is One Hit Wonders.</p> <p>Seating is limited, so show up on time to guarantee your seat!</p> <p>There is parking available behind the building, but public transportation is recommended if you’re drinking:) please send me message for any questions!</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1574479463000,
      duration: 5400000,
      id: 'nbjllrybcdbgc',
      name: 'A weekly fresh, fun and no judgement zone to flex your speaker muscles.',
      rsvp_limit: 20,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1582588800000,
      local_date: '2020-02-27',
      local_time: '19:00',
      updated: 1574479463000,
      utc_offset: -18000000,
      waitlist_count: 0,
      yes_rsvp_count: 4,
      venue: {
        id: 25828909,
        name: 'Element Hair',
        lat: 43.43887710571289,
        lon: -80.56260681152344,
        repinned: true,
        address_1: '1-350 The Boardwalk Street',
        city: 'Kitchener',
        country: 'ca',
        localized_country_name: 'Canada',
        zip: '',
        state: 'ON'
      },
      group: {
        created: 1539400816000,
        name: 'Waterloo Silver Tongue Toastmasters Meetup',
        id: 30265643,
        join_mode: 'open',
        lat: 43.470001220703125,
        lon: -80.58000183105469,
        urlname: 'Waterloo-Silver-Tongue-Toastmasters-Meetup',
        who: 'Members',
        localized_location: 'Waterloo, ON',
        state: 'ON',
        country: 'ca',
        region: 'en_US',
        timezone: 'Canada/Eastern'
      },
      link: 'https://www.meetup.com/Waterloo-Silver-Tongue-Toastmasters-Meetup/events/nbjllrybcdbgc/',
      description: '<p>Waterloo Silver Tongues! We\'re a Toastmasters Club meeting every Monday evening from 7:00-8:30pm at a unique location within Element Hair Salon at The Boardwalk in Waterloo Ontario.</p> <p>Silver Tongues are a a fresh, fun and no judgement zone to flex your speaker muscles. Our club is dedicated in helping each other build confidence to achieve greatness in all aspects of communication, including written and impromptu speeches, body language and listening.</p> <p>Experienced Toastmasters present the fundamentals of public speaking in a relaxed, enjoyable atmosphere. Members learn through an education program called Pathways, A learning experience tailored to your personal and professional goals and gives the member the opportunity to develop many skills relevant to an evolving global marketplace.</p> <p>The end result....you will become a more confident and poised speaker.</p> <p>If Your Dreams Don\'t Scare You They\'re Not Big Enough!</p> <p>Now more than ever is the time to find our voice</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1480556914000,
      duration: 7200000,
      id: 'lbzwgmybcgbkb',
      name: 'Toastmasters Meeting',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1586300400000,
      local_date: '2020-02-28',
      local_time: '19:00',
      updated: 1480556914000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 24057577,
        name: 'Allan Reuter Centre',
        lat: 43.39704513549805,
        lon: -80.36066436767578,
        repinned: false,
        address_1: '507 King Street East',
        city: 'Cambridge',
        country: 'ca',
        localized_country_name: 'Canada',
        zip: 'N3H 3N4',
        state: 'ON'
      },
      group: {
        created: 1441209834000,
        name: 'Grand River Toastmasters',
        id: 18892652,
        join_mode: 'open',
        lat: 43.400001525878906,
        lon: -80.36000061035156,
        urlname: 'Grand-River-Toastmasters',
        who: 'Toastmasters',
        localized_location: 'Cambridge, ON',
        state: 'ON',
        country: 'ca',
        region: 'en_US',
        timezone: 'Canada/Eastern'
      },
      link: 'https://www.meetup.com/Grand-River-Toastmasters/events/lbzwgmybcgbkb/',
      description: '<p>Come join us for an evening of fun and inspiration with impromptu and prepared short speeches.  Learn confidence among a group of supportive peers as we try our hand at public speaking within our group.</p> <p>Our meetings begin promptly every Tuesday at 7 pm and end at 9 pm.  Guests are warmly welcomed to participate or simply help cheer on our speakers.  This lively, welcoming, organized group is a fun way to spend a Tuesday night. Regardless of gender, race or occupation everyone can benefit from a dose of courage and encouragement.  Meet new friends while you grow personally.  We look forward to meeting you Tuesday night.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1568606651000,
      duration: 7200000,
      id: '264883974',
      name: 'TBA',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1582848000000,
      local_date: '2020-02-27',
      local_time: '19:00',
      updated: 1568606651000,
      utc_offset: -18000000,
      waitlist_count: 0,
      yes_rsvp_count: 26,
      group: {
        created: 1444910710000,
        name: 'Waterloo Data Science and Data Engineering',
        id: 19029662,
        join_mode: 'open',
        lat: 43.470001220703125,
        lon: -80.51000213623047,
        urlname: 'Waterloo-Data-Science-and-Data-Engineering',
        who: 'Data Enthousiasts',
        localized_location: 'Waterloo, ON',
        state: 'ON',
        country: 'ca',
        region: 'en_US',
        timezone: 'Canada/Eastern'
      },
      link: 'https://www.meetup.com/Waterloo-Data-Science-and-Data-Engineering/events/264883974/',
      description: '<p>TBA</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      local_time: '07:30',
      local_date: '2020-03-02',
      link: 'https://www.meetup.com/pm-connect-p2p/events/267077220/',
      visibility: 'public_limited',
      group: {
        created: 1415890696000,
        name: 'PM Connect P2P',
        id: 18186412,
        join_mode: 'approval',
        lat: 43.45000076293945,
        lon: -80.5,
        urlname: 'pm-connect-p2p',
        who: 'Peers',
        localized_location: 'Kitchener, ON',
        state: 'ON',
        country: 'ca',
        region: 'en_US',
        timezone: 'Canada/Eastern'
      },
      waitlist_count: 0,
      yes_rsvp_count: 19,
      duration: 5400000,
      time: 1584703800000,
      utc_offset: -14400000,
      name: 'To Be Announced',
      id: '267077220'
    },
    {
      created: 1578591864000,
      duration: 7200000,
      id: '267781702',
      name: 'Inverson of Control with TypeScript/JavaScript and How it Influences Testing',
      rsvp_limit: 80,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1582155000000,
      local_date: '2020-03-01',
      local_time: '18:30',
      updated: 1580239573000,
      utc_offset: -18000000,
      waitlist_count: 0,
      yes_rsvp_count: 77,
      venue: {
        id: 26110815,
        name: '25 Water St S',
        lat: 43.45063781738281,
        lon: -80.49434661865234,
        repinned: true,
        address_1: '25 Water St S',
        city: 'Kitchener',
        country: 'ca',
        localized_country_name: 'Canada',
        zip: 'N2G 4Z4',
        state: 'ON'
      },
      group: {
        created: 1543866771000,
        name: 'Tech Talks KW Hosted By Manulife',
        id: 30641823,
        join_mode: 'open',
        lat: 43.439998626708984,
        lon: -80.43000030517578,
        urlname: 'Manulife-Tech-Talks-KW',
        who: 'Techies',
        localized_location: 'Kitchener, ON',
        state: 'ON',
        country: 'ca',
        region: 'en_US',
        timezone: 'Canada/Eastern'
      },
      link: 'https://www.meetup.com/Manulife-Tech-Talks-KW/events/267781702/',
      description: '<p>We all want to write good code. While we know it’s impossible to write perfect code, we want to craft code that we aren’t embarrassed to put our names on for the documentation. Good Software Engineers write code that separates concerns, avoids tight coupling and interdependency between classes or methods, all while being easy to use and maintain. There are a number of different methods and patterns that help us achieve this, but one of the ways is through Inversion of Control (IoC) - the daughter pattern of dependency injection. Want to know how to do it with JavaScript/TypeScript? Want to know how to test it? See you on February 19th!</p> <p>Agenda:<br/>6pm: Doors Open<br/>6:30pm - 7:30pm: Tech Talk<br/>7:30pm - 8:15pm: Q&amp;A and Networking</p> <p>Gareth Sharpe is a Full-Stack Software Engineer at Manulife working on the Salesforce platform team developing GraphQL microservices for API consumers external to Salesforce. He likes mechanical keyboards, freshly ground coffee, relaxing symphony music, and squash.</p> <p>Location: Manulife, 25 Water St S Kitchener main entrance, meeting room Trinity B (entrance is right beside the Security desk – there will be signs with directions).</p> <p>Parking is free after 5:30PM at 25 Water: <a href=https://goo.gl/maps/gzaDn1NzKnS2 class=linkified>https://goo.gl/maps/gzaDn1NzKnS2</a></p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1480556914000,
      duration: 7200000,
      id: 'lbzwgmybchbhb',
      name: 'Toastmasters Meeting',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1588719600000,
      local_date: '2020-02-25',
      local_time: '19:00',
      updated: 1480556914000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 24057577,
        name: 'Allan Reuter Centre',
        lat: 43.39704513549805,
        lon: -80.36066436767578,
        repinned: false,
        address_1: '507 King Street East',
        city: 'Cambridge',
        country: 'ca',
        localized_country_name: 'Canada',
        zip: 'N3H 3N4',
        state: 'ON'
      },
      group: {
        created: 1441209834000,
        name: 'Grand River Toastmasters',
        id: 18892652,
        join_mode: 'open',
        lat: 43.400001525878906,
        lon: -80.36000061035156,
        urlname: 'Grand-River-Toastmasters',
        who: 'Toastmasters',
        localized_location: 'Cambridge, ON',
        state: 'ON',
        country: 'ca',
        region: 'en_US',
        timezone: 'Canada/Eastern'
      },
      link: 'https://www.meetup.com/Grand-River-Toastmasters/events/lbzwgmybchbhb/',
      description: '<p>Come join us for an evening of fun and inspiration with impromptu and prepared short speeches.  Learn confidence among a group of supportive peers as we try our hand at public speaking within our group.</p> <p>Our meetings begin promptly every Tuesday at 7 pm and end at 9 pm.  Guests are warmly welcomed to participate or simply help cheer on our speakers.  This lively, welcoming, organized group is a fun way to spend a Tuesday night. Regardless of gender, race or occupation everyone can benefit from a dose of courage and encouragement.  Meet new friends while you grow personally.  We look forward to meeting you Tuesday night.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1575656696000,
      duration: 10800000,
      id: 'phvtlrybcdbzb',
      name: 'Bitcoin Bay Kitchener-Waterloo',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1582153200000,
      local_date: '2020-03-02',
      local_time: '18:00',
      updated: 1579461783000,
      utc_offset: -18000000,
      waitlist_count: 0,
      yes_rsvp_count: 22,
      venue: {
        id: 26073899,
        name: 'Bobby O\'Brien\'s',
        lat: 43.45042037963867,
        lon: -80.49178314208984,
        repinned: false,
        address_1: '125 King St W',
        city: 'Kitchener',
        country: 'ca',
        localized_country_name: 'Canada',
        zip: 'N2G 1A7',
        state: 'ON'
      },
      group: {
        created: 1518721944000,
        name: 'BitCoin Bay Kitchener-Waterloo',
        id: 27532144,
        join_mode: 'open',
        lat: 43.45000076293945,
        lon: -80.48999786376953,
        urlname: 'BitCoin-Bay-Kitchener-Waterloo',
        who: 'Members',
        localized_location: 'Kitchener, ON',
        state: 'ON',
        country: 'ca',
        region: 'en_US',
        timezone: 'Canada/Eastern'
      },
      link: 'https://www.meetup.com/BitCoin-Bay-Kitchener-Waterloo/events/phvtlrybcdbzb/',
      description: '<p>The Bitcoin Bay is Toronto’s longest running and most popular blockchain and cryptocurrency meetup. Our goal is to foster education, innovation, and networking for like-minded people in the technology &amp; greater regional communities. We hold meetups in downtown Toronto, Mississauga, and Kitchener</p> <p>Community meetups are a big part of blockchain and cryptocurrency technology. We interact with others to ask questions and talk about different ideas and projects to build a more robust ecosystem.</p> <p>In the future we hope to build an inclusive, blockchain-agnostic, and flourishing community in Waterloo Region. Beyond our regional, provincial, and national borders - The Bitcoin Bay has been able to establish a flourishing WhatApp community from all over the globe. Be sure to ask about these groups to be added to them at our meetups</p> ',
      how_to_find_us: 'Ask the Hostess for the Bitcoin Bay KW Meetup',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1580776436000,
      duration: 7200000,
      id: '268438387',
      name: 'Panel: Experiences of Women & PoC in Customer-facing Roles',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1583449200000,
      local_date: '2020-03-02',
      local_time: '18:00',
      updated: 1580819575000,
      utc_offset: -18000000,
      waitlist_count: 0,
      yes_rsvp_count: 22,
      venue: {
        id: 26844479,
        name: 'Miovision',
        lat: 43.452213287353516,
        lon: -80.5137939453125,
        repinned: true,
        address_1: '137 Glasgow St',
        city: 'Kitchener',
        country: 'ca',
        localized_country_name: 'Canada',
        zip: 'N2G 4X8',
        state: 'ON'
      },
      group: {
        created: 1470316494000,
        name: 'Technical Support Innovators P2P',
        id: 20278638,
        join_mode: 'approval',
        lat: 43.439998626708984,
        lon: -80.43000030517578,
        urlname: 'Technical-Support-Innovators-P2P',
        who: 'Innovators',
        localized_location: 'Kitchener, ON',
        state: 'ON',
        country: 'ca',
        region: 'en_US',
        timezone: 'Canada/Eastern'
      },
      link: 'https://www.meetup.com/Technical-Support-Innovators-P2P/events/268438387/',
      description: '<p>Please join us on March 5th at 6pm in Miovison\'s office for an insightful panel on the biases, challenges, and experiences that affect women and PoC when dealing with customers. We have put together an accomplished panel who will share their experiences and ideas in a moderated discussion followed by an audience Q&amp;A.</p> <p>If you have any questions you would like to submit in advance, send a Meetup Message to Craig Stoss or post in your group message board.</p> <p>We will kick off with introductions at 6:15. Looking forward to seeing everyone!</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1568606752000,
      duration: 7200000,
      id: '264883999',
      name: 'TBA',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1585263600000,
      local_date: '2020-02-26',
      local_time: '19:00',
      updated: 1568606752000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 9,
      group: {
        created: 1444910710000,
        name: 'Waterloo Data Science and Data Engineering',
        id: 19029662,
        join_mode: 'open',
        lat: 43.470001220703125,
        lon: -80.51000213623047,
        urlname: 'Waterloo-Data-Science-and-Data-Engineering',
        who: 'Data Enthousiasts',
        localized_location: 'Waterloo, ON',
        state: 'ON',
        country: 'ca',
        region: 'en_US',
        timezone: 'Canada/Eastern'
      },
      link: 'https://www.meetup.com/Waterloo-Data-Science-and-Data-Engineering/events/264883999/',
      description: '<p>TBA</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1525108674000,
      duration: 7200000,
      id: 'qcmsqpybcdbgc',
      name: 'DevHouse Waterloo',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1582588800000,
      local_date: '2020-02-26',
      local_time: '19:00',
      updated: 1525108674000,
      utc_offset: -18000000,
      waitlist_count: 0,
      yes_rsvp_count: 51,
      venue: {
        id: 24481324,
        name: 'Shopify',
        lat: 43.46408462524414,
        lon: -80.52552032470703,
        repinned: false,
        address_1: '57 Erb St W',
        city: 'Waterloo',
        country: 'ca',
        localized_country_name: 'Canada',
        zip: '',
        state: 'ON'
      },
      group: {
        created: 1389456966000,
        name: 'DevHouse Waterloo',
        id: 12022872,
        join_mode: 'open',
        lat: 43.459999084472656,
        lon: -80.5199966430664,
        urlname: 'DevHouse-Waterloo',
        who: 'Members',
        localized_location: 'Waterloo, ON',
        state: 'ON',
        country: 'ca',
        region: 'en_US',
        timezone: 'Canada/Eastern'
      },
      link: 'https://www.meetup.com/DevHouse-Waterloo/events/qcmsqpybcdbgc/',
      description: '<p>DevHouse Waterloo is an event giving programmers and designers the opportunity to meet other creative people and learn from each other - whatever the topic may be.</p> <p>You can bring an idea, or a project you\'ve been working on, and present it to the group for feedback or help. Bits will be flowing (wifi is provided), projector will be available, food will be served, and space is provided by Shopify.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1525108674000,
      duration: 7200000,
      id: 'qcmsqpybcgbkc',
      name: 'DevHouse Waterloo',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1588028400000,
      local_date: '2020-02-27',
      local_time: '19:00',
      updated: 1525108674000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 5,
      venue: {
        id: 24481324,
        name: 'Shopify',
        lat: 43.46408462524414,
        lon: -80.52552032470703,
        repinned: false,
        address_1: '57 Erb St W',
        city: 'Waterloo',
        country: 'ca',
        localized_country_name: 'Canada',
        zip: '',
        state: 'ON'
      },
      group: {
        created: 1389456966000,
        name: 'DevHouse Waterloo',
        id: 12022872,
        join_mode: 'open',
        lat: 43.459999084472656,
        lon: -80.5199966430664,
        urlname: 'DevHouse-Waterloo',
        who: 'Members',
        localized_location: 'Waterloo, ON',
        state: 'ON',
        country: 'ca',
        region: 'en_US',
        timezone: 'Canada/Eastern'
      },
      link: 'https://www.meetup.com/DevHouse-Waterloo/events/qcmsqpybcgbkc/',
      description: '<p>DevHouse Waterloo is an event giving programmers and designers the opportunity to meet other creative people and learn from each other - whatever the topic may be.</p> <p>You can bring an idea, or a project you\'ve been working on, and present it to the group for feedback or help. Bits will be flowing (wifi is provided), projector will be available, food will be served, and space is provided by Shopify.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1581096923000,
      duration: 7200000,
      id: '268538422',
      name: 'Managing Complexity',
      rsvp_limit: 130,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1582243200000,
      local_date: '2020-03-02',
      local_time: '19:00',
      updated: 1581099240000,
      utc_offset: -18000000,
      waitlist_count: 21,
      yes_rsvp_count: 130,
      venue: {
        id: 24918400,
        name: 'Shopify',
        lat: 43.46408462524414,
        lon: -80.52552032470703,
        repinned: true,
        address_1: '57 Erb St W, Waterloo, ON N2L 6C2',
        city: 'Waterloo',
        country: 'ca',
        localized_country_name: 'Canada',
        zip: '',
        state: 'ON'
      },
      group: {
        created: 1409056854000,
        name: 'Shopify Tech Talks',
        id: 16610832,
        join_mode: 'open',
        lat: 43.45000076293945,
        lon: -80.4800033569336,
        urlname: 'shopify-tech-talks',
        who: 'Crafters',
        localized_location: 'Kitchener, ON',
        state: 'ON',
        country: 'ca',
        region: 'en_US',
        timezone: 'Canada/Eastern'
      },
      link: 'https://www.meetup.com/shopify-tech-talks/events/268538422/',
      description: '<p>Shopify removes unnecessary complexity from merchants\' lives, but sometimes that’s the nature of their business and complexity is essential. This month we’re going to dive into how we’re Managing Complexity in our Automation team.</p> <p>David Cameron will talk about the problems we are solving in our Automation team, and the challenges that come with building products that are platforms rather than solutions to specific problems.</p> <p>Mitch Dickinson will talk about how complexity can be managed by allowing third parties to inject custom code into a system. By allowing merchants and partners to provide their own code for a complex process, we can avoid having to build that complexity into our core for all merchants. We will go deep, exploring how Shopify is trying to solve this using a serverless WebAssembly runtime to host untrusted code.</p> <p>José Torre will talk about how to make complexity accessible. Reflecting on the process of redesigning an app that is meant to bring the power of automation to the hands of merchants. Sharing lessons learned and what he would have done differently if he started tackling the problem now.</p> <p>As always, we\'ll have food and drinks to enjoy throughout the evening.</p> <p>## What to expect:</p> <p>The talks cover the complexity of building automations and customizations from 3 very different perspectives — product, engineering and design. No matter your background, you’ll walk away learning something new.</p> <p>## Who are the speakers?</p> <p>David Cameron (<a href=https://www.linkedin.com/in/davidjcameron/ class=linkifie>https://www.linkedin.com/in/davidjcameron/</a>) is a Product Lead at Shopify. He leads the product direction for our Automation products Shopify Flow, Shopify Scripts, and Launchpad. He also enjoys automating his home and finding delightful solutions to problems.</p> <p>Mitch Dickinson (<a href=https://www.linkedin.com/in/mitchdickinson/ class=linkified>https://www.linkedin.com/in/mitchdickinson/</a>) is a Development Manager at Shopify. He has been leading the efforts to rebuild Shopify Scripts (<a href=https://help.shopify.com/en/manual/apps/apps-by-shopify/script-editor class=linkified>https://help.shopify.com/en/manual/apps/apps-by-shopify/script-editor</a>), to make a more extensible commerce platform for all merchants. He loves elegant software design, DDD, and databases. He joined Shopify 16 months ago and has a background of working for startups in the Waterloo region.</p> <p>José Torre (<a href=https://www.linkedin.com/in/jos%C3%A9-torre-3979b821/class=linkified>https://www.linkedin.com/in/jos%C3%A9-torre-3979b821/</a>) is a staff product designer at Shopify, where he has been working for almost 6 months. He joined the Automation team with the task of redesigning Flow, a workflow automation app. In his spare time he writes n Medium about design (<a href=https://medium.com/@zecarlostorre class=linkified>https://medium.com/@zecarlostorre</a>).</p> <p>## Is this event for you?</p> <p>This event is intended for anyone with an interest in building software products, whether it be technical, design, or product. The talks are all approachable regardless of your background!</p> <p>Our office is fully accessible and we have gender neutral facilities available on site. Should you require any additional accommodations, please let us know as soon as possible.</p> ',
      how_to_find_us: 'The front door is located on the west side of building, near the entrance to CIGI.',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1525108674000,
      duration: 7200000,
      id: 'qcmsqpybcfbnc',
      name: 'DevHouse Waterloo',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1585609200000,
      local_date: '2020-03-30',
      local_time: '19:00',
      updated: 1525108674000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 13,
      venue: {
        id: 24481324,
        name: 'Shopify',
        lat: 43.46408462524414,
        lon: -80.52552032470703,
        repinned: false,
        address_1: '57 Erb St W',
        city: 'Waterloo',
        country: 'ca',
        localized_country_name: 'Canada',
        zip: '',
        state: 'ON'
      },
      group: {
        created: 1389456966000,
        name: 'DevHouse Waterloo',
        id: 12022872,
        join_mode: 'open',
        lat: 43.459999084472656,
        lon: -80.5199966430664,
        urlname: 'DevHouse-Waterloo',
        who: 'Members',
        localized_location: 'Waterloo, ON',
        state: 'ON',
        country: 'ca',
        region: 'en_US',
        timezone: 'Canada/Eastern'
      },
      link: 'https://www.meetup.com/DevHouse-Waterloo/events/qcmsqpybcfbnc/',
      description: '<p>DevHouse Waterloo is an event giving programmers and designers the opportunity to meet other creative people and learn from each other - whatever the topic may be.</p> <p>You can bring an idea, or a project you\'ve been working on, and present it to the group for feedback or help. Bits will be flowing (wifi is provided), projector will be available, food will be served, and space is provided by Shopify.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1480556914000,
      duration: 7200000,
      id: 'lbzwgmybcgbcc',
      name: 'Toastmasters Meeting',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1587510000000,
      local_date: '2020-04-21',
      local_time: '19:00',
      updated: 1480556914000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 24057577,
        name: 'Allan Reuter Centre',
        lat: 43.39704513549805,
        lon: -80.36066436767578,
        repinned: false,
        address_1: '507 King Street East',
        city: 'Cambridge',
        country: 'ca',
        localized_country_name: 'Canada',
        zip: 'N3H 3N4',
        state: 'ON'
      },
      group: {
        created: 1441209834000,
        name: 'Grand River Toastmasters',
        id: 18892652,
        join_mode: 'open',
        lat: 43.400001525878906,
        lon: -80.36000061035156,
        urlname: 'Grand-River-Toastmasters',
        who: 'Toastmasters',
        localized_location: 'Cambridge, ON',
        state: 'ON',
        country: 'ca',
        region: 'en_US',
        timezone: 'Canada/Eastern'
      },
      link: 'https://www.meetup.com/Grand-River-Toastmasters/events/lbzwgmybcgbcc/',
      description: '<p>Come join us for an evening of fun and inspiration with impromptu and prepared short speeches.  Learn confidence among a group of supportive peers as we try our hand at public speaking within our group.</p> <p>Our meetings begin promptly every Tuesday at 7 pm and end at 9 pm.  Guests are warmly welcomed to participate or simply help cheer on our speakers.  This lively, welcoming, organized group is a fun way to spend a Tuesday night. Regardless of gender, race or occupation everyone can benefit from a dose of courage and encouragement.  Meet new friends while you grow personally.  We look forward to meeting you Tuesday night.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1579905557000,
      duration: 7200000,
      id: '268179877',
      name: 'Recruiting and Hiring for Sales Panel',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1582030800000,
      local_date: '2020-03-18',
      local_time: '08:00',
      updated: 1580497385000,
      utc_offset: -18000000,
      waitlist_count: 0,
      yes_rsvp_count: 23,
      venue: {
        id: 26651430,
        name: 'Communitech, Roddenberry Room',
        lat: 43.45095443725586,
        lon: -80.4981689453125,
        repinned: true,
        address_1: '151 Charles Street West, 3rd Floor',
        city: 'Kitchener',
        country: 'ca',
        localized_country_name: 'Canada',
        zip: 'N2G 1H6',
        state: 'on'
      },
      group: {
        created: 1406735729000,
        name: 'Sales Leaders P2P',
        id: 16079362,
        join_mode: 'approval',
        lat: 43.45000076293945,
        lon: -80.5,
        urlname: 'sales-leaders-p2p',
        who: 'Peers',
        localized_location: 'Kitchener, ON',
        state: 'ON',
        country: 'ca',
        region: 'en_US',
        timezone: 'Canada/Eastern'
      },
      link: 'https://www.meetup.com/sales-leaders-p2p/events/268179877/',
      description: '<p>Join the Sales Leaders P2P for an interactive panel session on Recruiting and Hiring for Sales. This session will cover a wide range of topics such as; how to find the right candidate, how to evaluate fit, closing, and how to engage and keep top talent. Our panel consists of a dynamic group of sales and human resource leaders from our community:</p> <p>Phil McRoberts, Director of Inside Sales, ApplyBoard<br/>ApplyBoard has helped more than 70,000 students around the world with their academic journey, becoming the world’s largest platform for international student recruitment to Canada and the United States. Phil is responsible for ApplyBoard’s Direct Sales strategy and has held numerous Sales and Business Development leadership roles within the Waterloo Region Tech Sector.</p> <p>Luke Morrison, Managing Director, Procom<br/>Luke has an Honours BBA from Wilfrid Laurier and 18 years of staffing experience at Procom. He has worked in Toronto and Kitchener- Waterloo and currently manages the sales and recruitment delivery teams in Kitchener-Waterloo and manages several large scale North American contingent staffing programs including Manulife/John Hancock, Sunlife Financial and Enbridge.</p> <p>Bogdan Oros, Director of Business Development, Alert Labs<br/>Alert Labs provides direct to cloud cellular sensors that are helping customers save on utility bills and prevent water damage to their properties. Bogdan is responsible for growing the customer base and channel of partners in the commercial space. He has 10 years of international experience in growing start-ups, building sales teams in the IoT and security space in Europe.</p> <p>Taylor Soock, People Specialist, Auvik Networks<br/>Auvik is a venture-backed company making software that\'s changing the way IT networks are managed. We\'re solving the problems of network complexity so our customers don\'t have to. Taylor started in tech at Atomic (now Terminal) as a recruiter with previous experience in the role at an agency. When she moved to Auvik in 2017, Taylor built the recruiting process to almost double the size of the company in less than a year. She is now the HR Business Partner, working with every department to run a variety of programs focused on employee retention and development.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      local_time: '07:30',
      local_date: '2020-03-21',
      link: 'https://www.meetup.com/pm-connect-p2p/events/267077174/',
      visibility: 'public_limited',
      group: {
        created: 1415890696000,
        name: 'PM Connect P2P',
        id: 18186412,
        join_mode: 'approval',
        lat: 43.45000076293945,
        lon: -80.5,
        urlname: 'pm-connect-p2p',
        who: 'Peers',
        localized_location: 'Kitchener, ON',
        state: 'ON',
        country: 'ca',
        region: 'en_US',
        timezone: 'Canada/Eastern'
      },
      waitlist_count: 0,
      yes_rsvp_count: 39,
      duration: 5400000,
      time: 1582288200000,
      utc_offset: -18000000,
      name: 'PM to PM',
      id: '267077174'
    },
    {
      local_time: '07:30',
      local_date: '2020-04-17',
      link: 'https://www.meetup.com/pm-connect-p2p/events/267077270/',
      visibility: 'public_limited',
      group: {
        created: 1415890696000,
        name: 'PM Connect P2P',
        id: 18186412,
        join_mode: 'approval',
        lat: 43.45000076293945,
        lon: -80.5,
        urlname: 'pm-connect-p2p',
        who: 'Peers',
        localized_location: 'Kitchener, ON',
        state: 'ON',
        country: 'ca',
        region: 'en_US',
        timezone: 'Canada/Eastern'
      },
      waitlist_count: 0,
      yes_rsvp_count: 20,
      duration: 5400000,
      time: 1587123000000,
      utc_offset: -14400000,
      name: 'Book Club',
      id: '267077270'
    },
    {
      created: 1571002170000,
      duration: 7200000,
      id: 'bmjckrybcdbhc',
      name: 'Topic TBD',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1582675200000,
      local_date: '2020-03-25',
      local_time: '19:00',
      updated: 1571002170000,
      utc_offset: -18000000,
      waitlist_count: 0,
      yes_rsvp_count: 8,
      venue: {
        id: 26681072,
        name: 'Agilicus Incorporated',
        lat: 43.4503173828125,
        lon: -80.49085998535156,
        repinned: false,
        address_1: '87 King St W',
        city: 'Kitchener',
        country: 'ca',
        localized_country_name: 'Canada',
        zip: 'N2G 1A7',
        state: 'ON'
      },
      group: {
        created: 1531924312000,
        name: 'Waterloo Technology Chautauqua',
        id: 29287490,
        join_mode: 'open',
        lat: 43.45000076293945,
        lon: -80.48999786376953,
        urlname: 'Waterloo-Technology-Chautauqua',
        who: 'Members',
        localized_location: 'Kitchener, ON',
        state: 'ON',
        country: 'ca',
        region: 'en_US',
        timezone: 'Canada/Eastern'
      },
      link: 'https://www.meetup.com/Waterloo-Technology-Chautauqua/events/bmjckrybcdbhc/',
      description: '<p>RSVP in case we get snacks!</p> ',
      how_to_find_us: 'ION! or park behind off ontario/halls lane. Or duke garage',
      visibility: 'public',
      member_pay_fee: false
    }
  ]
};

export { mockEvents };